---
settings:
  site_name: deveb
  gtm_id: gtm123
  ga_id: ga123
  fb_id: fb1234
images:
  favicon: "/images/system/favicon.jpg"
  profile: "/images/system/profile.jpg"
profile:
  name: DC
  email: dc@gmail.com
  summary: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta amet
    nemo quae sed architecto dolorum modi doloremque, necessitatibus velit, ipsum
    error explicabo? Temporibus tenetur necessitatibus ab eaque odit possimus sapiente
    minima dolor, asperiores magnam non officiis natus ipsam.</p>\r\n"
