---
settings:
  site_name: deveb
  gtm_id: ''
  ga_id: UA-116661792-1
  fb_id: ''
images:
  favicon: "/images/system/favicon.jpg"
  profile: "/images/system/profile.jpg"
profile:
  name: DC
  email: dachang.dev@gmail.com
  github: DC7806
  summary: '<p style="text-align: center;">A digital marketer who loves building web
    apps</p>'
