---
settings:
  site_name: deveb
  gtm_id: ''
  ga_id: UA-116661792-1
  fb_id: ''
images:
  favicon: "/images/system/favicon.jpg"
  profile: "/images/system/profile.jpg"
profile:
  name: DC
  email: dc@gmail.com
  summary: "<p style=\"text-align: center;\">A digital marketer who loves building
    web apps</p>\r\n\r\n<p style=\"text-align: center;\"><a href=\"https://github.com/DC7806\"
    target=\"_blank\"><i class=\"fa fa-github fa-2x\" aria-hidden=\"true\"></i></a></p>\r\n"
